version: '3'

services:
  app:
    image: 'node:lts'
    working_dir: '/home/node/app'
    volumes:
      - ./:/home/node/app
    user: '1000'
    ports:
      - '${PORT}:${PORT}'
    command: 'npm start'
